includes = [".dotter/macos.toml"]
packages = [
  "zsh",
  "nushell",
  "git",
  "nix-darwin",
  "direnv",
  "zed",
  "ghostty",
  "helix",
  "yazi",
  "zellij",
  "atuin",
  "bat",
  "marimo",
  "btop",
  "tlrc",
  "lazygit",
  "gitui",
  "starship",
  "fastfetch",
  "opencode",
  "harlequin",
  "rumdl",
  "prettier",
  "oxc",
]
