includes = [".dotter/macos.toml"]
packages = [
  "zsh",
  "git",
  "nix-darwin",
  "direnv",
  "zed",
  "ghostty",
  "helix",
  "yazi",
  "zellij",
  "atuin",
  "marimo",
  "btop",
  "julia",
  "starship",
]
