[nix-darwin.files]
".config/nix-darwin/flake.nix" = "/Users/nickminor/.config/nix-darwin/flake.nix"
".config/nix-darwin/flake.lock" = "/Users/nickminor/.config/nix-darwin/flake.lock"

[direnv.files]
".direnvrc" = "/Users/nickminor/.direnvrc"
".config/nix-direnv/config.toml" = "/Users/nickminor/.config/nix-direnv/config.toml"

[ghostty.files]
".config/ghostty/config" = "/Users/nickminor/Library/Application Support/com.mitchellh.ghostty/config"

[zsh.files]
".zshrc" = "/Users/nickminor/.zshrc"
".zprofile" = "/Users/nickminor/.zprofile"
".zshenv" = "/Users/nickminor/.zshenv"

[git.files]
".gitconfig" = "/Users/nickminor/.gitconfig"

[helix.files]
".config/helix/config.toml" = "/Users/nickminor/.config/helix/config.toml"
".config/helix/languages.toml" = "/Users/nickminor/.config/helix/languages.toml"
".config/helix/runtime/themes/custom.toml" = "/Users/nickminor/.config/helix/runtime/themes/custom.toml"
".config/helix/runtime/themes/catppuccin_macchiato.toml" = "/Users/nickminor/.config/helix/runtime/themes/catppuccin_macchiato.toml"
".config/helix/runtime/themes/catppuccin_mocha.toml" = "/Users/nickminor/.config/helix/runtime/themes/catppuccin_mocha.toml"

[zed.files]
".config/zed/settings.json" = "/Users/nickminor/.config/zed/settings.json"
".config/zed/keymap.json" = "/Users/nickminor/.config/zed/keymap.json"

[yazi.files]
".config/yazi/yazi.toml" = "/Users/nickminor/.config/yazi/yazi.toml"
".config/yazi/theme.toml" = "/Users/nickminor/.config/yazi/theme.toml"

[zellij.files]
".config/zellij/config.kdl" = "/Users/nickminor/.config/zellij/config.kdl"

[atuin.files]
".config/atuin/config.toml" = "/Users/nickminor/.config/atuin/config.toml"

[btop.files]
".config/btop/btop.conf" = "/Users/nickminor/.config/btop/btop.conf"

[julia.files]
".config/julia/config/startup.jl" = "/Users/nickminor/.julia/config/startup.jl"

[marimo.files]
".marimo.toml" = "/Users/nickminor/.marimo.toml"

[starship.files]
".config/starship.toml" = "/Users/nickminor/.config/starship.toml"

