[experimental]

[completion]
activate_on_typing = true
copilot = false

[save]
format_on_save = true
autosave_delay = 1000
autosave = "after_delay"

[display]
default_width = "medium"
cell_output = "below"
dataframes = "rich"
reference_highlighting = false
default_table_page_size = 30
code_editor_font_size = 12
default_table_max_columns = 50
theme = "system"

[formatting]
line_length = 79

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[diagnostics]
sql_linter = true

[server]
browser = "default"
follow_symlink = false

[snippets]
include_default_snippets = true
custom_paths = []

[package_management]
manager = "uv"

[datasources]

[mcp]
presets = []

[mcp.mcpServers]

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_pyflakes = false
enabled = false
enable_pylint = false
enable_pydocstyle = false
enable_flake8 = false
enable_mypy = true
enable_ruff = true

[runtime]
auto_instantiate = true
on_cell_change = "autorun"
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
reactive_tests = true
auto_reload = "autorun"
output_max_bytes = 8000000
default_auto_download = []
default_sql_output = "auto"

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.open_ai]

[ai.models]
displayed_models = []
custom_models = []
