theme = "custom"

[editor]
line-number = "relative"
mouse = true
auto-pairs = true
rulers = [88]
cursorline = true
cursorcolumn = false
bufferline = "always"
# end-of-line-diagnostics = "error"
color-modes = true
popup-border = "all"
idle-timeout = 250     # 250 is the default
completion-timeout = 5 # time for auto-completion to appear. 5 is instant, 250 is the default
# completion-replace = true
undercurl = true
indent-heuristic = "tree-sitter"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
# shell = ["nu", "--stdin", "-c"]

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"
max-diagnostics = 10
prefix-len = 2
max-wrap = 40

[editor.soft-wrap]
enable = true
wrap-at-text-width = false
wrap-indicator = "  "

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â•Ž"
render = true

[editor.file-picker]
hidden = false
follow-symlinks = true
# git-ignore = false
parents = false # ignore .gitignore files in parent directories

[editor.smart-tab]
enable = true

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = []
right = [
  "diagnostics",
  "selections",
  # "register",
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-encoding",
  # "file-line-ending",
  "file-type",
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Cmd-r = ":reload-all"
C-s = ":w"
Cmd-s = ":write"
"Cmd-p" = ":sh echo -n %{buffer_name} | pbcopy"
"Cmd-c" = ":sh echo -n %{buffer_name} | pbcopy"
"ret" = "goto_word"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
# the following settings keep the LSP from yelling at you about invalid syntax
# before you're done typing
i = [":toggle-option end-of-line-diagnostics disable", "insert_mode"]
I = [":toggle-option end-of-line-diagnostics disable", "insert_at_line_start"]
a = [":toggle-option end-of-line-diagnostics disable", "append_mode"]
A = [":toggle-option end-of-line-diagnostics disable", "insert_at_line_end"]
o = [":toggle-option end-of-line-diagnostics disable", "open_below"]
O = [":toggle-option end-of-line-diagnostics disable", "open_above"]
c = [":toggle-option end-of-line-diagnostics disable", "change_selection"]

[keys.select]
"ret" = "goto_word"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

[keys.insert]
esc = [":toggle-option end-of-line-diagnostics error", "normal_mode"]
