#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Nick Minor"
email = "nicholasrminor@gmail.com"

[ui]
default-command = ["log", "--no-pager", "--reversed"]
diff-editor = ":builtin"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
